services:

  mysql:
    image: mysql:8

    container_name: mysql_db

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: enviosdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend_despachos:
    build: ./back-Despachos_SpringBoot

    container_name: backend_despachos

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/enviosdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: app123

    depends_on:
      mysql:
        condition: service_healthy

  backend_ventas:
    build: ./back-Ventas_SpringBoot

    container_name: backend_ventas

    ports:
      - "8081:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/enviosdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: app123

    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./front_despacho

    container_name: frontend_app

    ports:
      - "3000:80"

    depends_on:
      - backend_despachos
      - backend_ventas

volumes:
  mysql_data: